require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.null-ls")
require("user.prettier")
require("user.web-devicons")
require("user.lualine")
require("user.nvim-tree")
require("user.toggleterm")
require("user.indent_blankline")
require("user.treesitter")
require("user.gitsigns")
-- require("user.multiple-cursors")
